# Generated by Django 4.2.2 on 2023-10-12 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode_kelas", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Daftar Kelas",
                "ordering": ("kode_kelas",),
            },
        ),
        migrations.CreateModel(
            name="Matkul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul_matkul", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "List Mata Kuliah",
                "ordering": ("judul_matkul",),
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul_quiz", models.CharField(max_length=200)),
                ("waktu_pengerjaan", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Soal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_soal", models.TextField()),
                ("jawaban_benar", models.CharField(max_length=1)),
                (
                    "quiz_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soal_quiz",
                        to="portal.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Soal",
                "ordering": ("quiz_id",),
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lengkap", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("MAHASISWA", "MAHASISWA"), ("DOSEN", "DOSEN")],
                        max_length=20,
                    ),
                ),
                ("nid", models.CharField(blank=True, max_length=50, null=True)),
                ("nim", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "kelas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="kelas",
                        to="portal.kelas",
                    ),
                ),
                ("matkul_diajar", models.ManyToManyField(to="portal.matkul")),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data User",
                "ordering": ("nama_lengkap",),
            },
        ),
        migrations.CreateModel(
            name="RiwayatPengerjaanQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_pengerjaan", models.DateTimeField(auto_now_add=True)),
                ("nilai", models.IntegerField()),
                (
                    "mahasiswa_id",
                    models.ForeignKey(
                        limit_choices_to={"role": "MAHASISWA"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="quiz_dikerjakan",
                        to="portal.role",
                    ),
                ),
                (
                    "quiz_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="quiz_terkait",
                        to="portal.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Riwayat Pengerjaan Quiz",
                "ordering": ("mahasiswa_id",),
            },
        ),
        migrations.AddField(
            model_name="matkul",
            name="dosen_pengampu",
            field=models.ManyToManyField(
                limit_choices_to={"role": "DOSEN"}, to="portal.role"
            ),
        ),
        migrations.CreateModel(
            name="Materi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul_materi", models.CharField(max_length=200)),
                ("url_video", models.TextField(blank=True, null=True)),
                ("video_text_transcript", models.TextField(blank=True, null=True)),
                ("file_materi", models.FileField(upload_to="dokumen_materi")),
                (
                    "dosen_pembuat",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOSEN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosen_pengajar",
                        to="portal.role",
                    ),
                ),
                (
                    "matkul_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materi_matkul",
                        to="portal.matkul",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Materi",
                "ordering": ("judul_materi",),
            },
        ),
        migrations.AddField(
            model_name="kelas",
            name="daftar_matkul",
            field=models.ManyToManyField(to="portal.matkul"),
        ),
        migrations.CreateModel(
            name="Jawaban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_jawaban", models.CharField(max_length=200)),
                (
                    "soal_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jawaban_soal",
                        to="portal.soal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Jawaban",
                "ordering": ("soal_id",),
            },
        ),
    ]
