# Generated by Django 4.2.2 on 2023-10-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ("judul_quiz",), "verbose_name_plural": "List Quiz"},
        ),
        migrations.AddField(
            model_name="quiz",
            name="dibuat_oleh",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "DOSEN"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dosen_pembuat",
                to="portal.role",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="materi_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materi_quiz",
                to="portal.materi",
            ),
        ),
    ]
