# Generated by Django 4.2.2 on 2023-10-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_quiz_options_quiz_dibuat_oleh_quiz_materi_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kelas",
            name="daftar_matkul",
            field=models.ManyToManyField(blank=True, null=True, to="portal.matkul"),
        ),
    ]
