# Generated by Django 4.2.2 on 2023-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_kelas_daftar_matkul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="matkul_diajar",
            field=models.ManyToManyField(blank=True, null=True, to="portal.matkul"),
        ),
    ]
