# Generated by Django 4.2.2 on 2023-10-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_alter_role_matkul_diajar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kelas",
            name="daftar_matkul",
            field=models.ManyToManyField(blank=True, to="portal.matkul"),
        ),
        migrations.AlterField(
            model_name="role",
            name="matkul_diajar",
            field=models.ManyToManyField(blank=True, to="portal.matkul"),
        ),
    ]
