# Generated by Django 4.2.2 on 2023-10-13 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_alter_kelas_daftar_matkul_alter_role_matkul_diajar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jawaban",
            options={"ordering": ("soal",), "verbose_name_plural": "List Jawaban"},
        ),
        migrations.RenameField(
            model_name="jawaban",
            old_name="soal_id",
            new_name="soal",
        ),
        migrations.RenameField(
            model_name="materi",
            old_name="matkul_id",
            new_name="matkul",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="materi_id",
            new_name="materi",
        ),
        migrations.RenameField(
            model_name="riwayatpengerjaanquiz",
            old_name="mahasiswa_id",
            new_name="mahasiswa",
        ),
        migrations.RenameField(
            model_name="riwayatpengerjaanquiz",
            old_name="quiz_id",
            new_name="quiz",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="soal",
            old_name="quiz_id",
            new_name="quiz",
        ),
    ]
