# Generated by Django 4.2.2 on 2023-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_jawaban_options_rename_soal_id_jawaban_soal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materi",
            name="file_materi",
            field=models.FileField(blank=True, null=True, upload_to="dokumen_materi"),
        ),
    ]
