# Generated by Django 4.2.2 on 2023-10-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_alter_materi_file_materi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matkul",
            name="dosen_pengampu",
        ),
        migrations.AddField(
            model_name="matkul",
            name="dosen_pengampu",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materi_diajar",
                to="portal.role",
            ),
            preserve_default=False,
        ),
    ]
