# Generated by Django 4.2.2 on 2023-10-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_soal_jawaban_a_soal_jawaban_b_soal_jawaban_c_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soal",
            name="jawaban_a",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="soal",
            name="jawaban_b",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="soal",
            name="jawaban_c",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="soal",
            name="jawaban_d",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
