# Generated by Django 4.2.2 on 2023-11-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0013_testapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="materi",
            name="link_materi",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
